### ISSUE TITLE
No rasters for Alaska or Hawaii

### ISSUE THREAD

**Issue by krosepulham** [OSUCliMates/DataDash#11]
@empalmer your lovely implementation of Jess's brushed points interface includes Alaska and Hawaii, but when those states are selected we get an error code since they're not in our data sets. 

Also, is there a way to automatically zoom nationwide as if it were a state? for example, if we wanted to look at the area that stretches from the Western border of Idaho to the Western border of Minnesota, currently we'd need to press "zoom out" a bunch which is a little inconvenient.

**Comment by empalmer** [comment]
Now tells user to select another state if Hawaii or Alaska is selected 

"United States" is now an option of a "state" to view entire US
