### ISSUE TITLE
error won't let app run

### ISSUE THREAD

**Issue by ericka-howard** [OSUCliMates/DataDash#19]
I chased this a little but then figured I should just ask, getting this error:
Warning: Error in mean: object 'diff_from_prec_mean' not found
  60: summarise_impl
  59: summarise.tbl_df
  57: function_list[[i]]
  56: freduce
  55: _fseq
  54: eval
  53: eval
  51: %>%
  50: get_us_precip_deviation [setup_plot_maps.R#95]
  49: server [/home/smither8/DataDash/server.R#178]
Error in mean(diff_from_prec_mean) : 
  object 'diff_from_prec_mean' not found

(and the app won't run). I think it's just something in the newest pull request

**Comment by empalmer** [comment]
fixed by latest PR
