### ISSUE TITLE
missing waveforms csv

### ISSUE THREAD

**Issue by ericka-howard** [OSUCliMates/DataDash#4]
Are you keeping decadal_average_cumulative_prec_waveforms.csv in the repo or are you creating it each time? It's throwing an error when trying to run the app.

**Comment by krosepulham** [comment]
That's the 400+MB file that I had to precompute. GitHub won't let you upload anything that big, so I wasn't able to put it in the repo.

Edit: to be clear, this data set gets generated by running the sawtooth.R script. This is a massive data reduction and takes a couple hours to run, even optimized using purrr. We'll talk more about where we want this data to live in our meeting in an hour and a half.
